apiVersion: v1
kind: ConfigMap
metadata:
  name: wipp-registry-superuser-configmap
data:
  createsuperuser.sh: |
    echo "Creating super user..."
    python ./manage.py shell -c  "from django.contrib.auth.models import User; User.objects.create_superuser('$SUPERUSER_USERNAME', '$SUPERUSER_EMAIL', '$SUPERUSER_PASSWORD')"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: wipp-registry-create-superuser
spec:
  template:
    spec:
      containers:
      - image: wipp/wipp-registry:1.1.0
        name: cdcs
        command: ['/bin/bash', '/srv/curator/createsuperuser.sh']
        envFrom:
        - secretRef:
            name: wipp-registry-superuser
        - secretRef:
            name: wipp-registry-cdcs
        volumeMounts:
          - name: wipp-registry-superuser-config
            mountPath: /srv/curator/createsuperuser.sh
            subPath: createsuperuser.sh
      volumes:
      - name: wipp-registry-superuser-config
        configMap:
          name: wipp-registry-superuser-configmap
      restartPolicy: Never
  backoffLimit: 4