apiVersion: apps/v1
kind: Deployment
metadata:
  name: wipp-registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: wipp-registry
  template:
    metadata:
      labels:
        component: wipp-registry
    spec:
      containers:
      - image: wipp/wipp-registry:1.1.0
        name: cdcs
        command: ['/docker-entrypoint-gunicorn.sh']
        args: ["nmrr"]
        envFrom:
        - secretRef:
            name: wipp-registry-cdcs
        ports:
        - containerPort: 8000
      restartPolicy: Always